<?php
/** @package Beatriz::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ChecklistvistoriaMap.php");

/**
 * ChecklistvistoriaDAO provides object-oriented access to the checklistvistoria table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Beatriz::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ChecklistvistoriaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Vistoriaid;

	/** @var int */
	public $Questaoid;

	/** @var string */
	public $Tipoavaliacao;

	/** @var string */
	public $Observacao;


	/**
	 * Returns the foreign object based on the value of Questaoid
	 * @return Questao
	 */
	public function GetQuestaoidQuestao()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_checklistvistoria_questao");
	}

	/**
	 * Returns the foreign object based on the value of Vistoriaid
	 * @return Vistoria
	 */
	public function GetVistoriaidVistoria()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_checklistvistoria_vistoria");
	}


}
?>