<?php
/** @package Beatriz::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EngenheiroMap.php");

/**
 * EngenheiroDAO provides object-oriented access to the engenheiro table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Beatriz::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EngenheiroDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;


	/**
	 * Returns a dataset of Vistoria objects with matching Engenheiroid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetEngenheiroidVistorias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_vistoria_engenheiro_idx", $criteria);
	}


}
?>