<?php
/** @package Beatriz::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("QuestaoMap.php");

/**
 * QuestaoDAO provides object-oriented access to the questao table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Beatriz::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class QuestaoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Descricao;

	/** @var int */
	public $Grupoquestaoid;


	/**
	 * Returns a dataset of Checklistvistoria objects with matching Questaoid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetQuestaoidChecklistvistorias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_checklistvistoria_questao", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Grupoquestaoid
	 * @return Grupoquestao
	 */
	public function GetGrupoquestaoidGrupoquestao()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_questao_grupo");
	}
        
        public function GetAll()
        {
            return ;
        }
                


}
?>