<?php
/** @package Beatriz::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("VistoriaMap.php");

/**
 * VistoriaDAO provides object-oriented access to the vistoria table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Beatriz::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class VistoriaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var date */
	public $Data;

	/** @var int */
	public $Obraid;
	/** @var intNome */
	public $ObraNome;

	/** @var int */
	public $EngenheiroNome;

	/** @var int */
	public $Engenheiroid;


	/**
	 * Returns a dataset of Checklistvistoria objects with matching Vistoriaid
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetVistoriaidChecklistvistorias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_checklistvistoria_vistoria", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Engenheiroid
	 * @return Engenheiro
	 */
	public function GetEngenheiroidEngenheiro()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_vistoria_engenheiro_idx");
	}

	/**
	 * Returns the foreign object based on the value of Obraid
	 * @return Obra
	 */
	public function GetObraidObra()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_vistoria_obra_idx");
	}


}
?>